var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Re-judgment of Claim Debt)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select Assessing period(1)","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Select Assessing period(2)","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Select Sort items(1)","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Select Sort items(2)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Select Sort order(1)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Select Sort order(2)","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Select Displaying the number of items(1)","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;Select Displaying the number of items(2)","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;Select Cust.Code","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;Verify Take","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;Show Comment(1)","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;Show Comment(2)","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;Confirm details","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;Confirm Claim Debt checkbox","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;Input the Reason for the Judgment","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;Save details","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;Select the Authorizer(1)","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;Select the Authorizer(2)","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;Register","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;End","s_20.htm","course"));
