var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main menu(List Download)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select a List type(1)","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Select a List type(2)","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Input a Assessing Period","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Select a Quarter(1)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Select a Quarter(2)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Input Month/Year","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Input A/C CD","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;Input DUNS No.","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;Input A/C Name","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;Select Company(1)","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;Select Company(2)","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;Select Dept.(1)","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;Select Dept.(2)","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;Click Download","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;Confirm Download","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;Macro Settings","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;End","s_17.htm","course"));
