var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（進捗状況照会 および 取り戻し）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;対象年月入力","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;勘定先CD入力","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;DUNS No.入力","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;勘定先名称入力","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;所在国選択①","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;所在国選択②","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;フェーズ選択①","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;フェーズ選択②","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;ステータス選択①","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;ステータス選択②","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;査定会社選択①","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;査定会社選択②","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;部門選択①","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;部門選択②","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;部選択①","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;部選択②","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;関係者入力","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;処理日From入力","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;処理日To入力","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;表示件数選択①","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;表示件数選択②","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp;検索実行","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;詳細画面へ遷移","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;詳細画面_査定タブ","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;詳細画面_実質滞留判定タブ","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;取り戻し","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;終了","s_27.htm","course"));
