var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Input user ID","s_1.htm","course"));
var stepFrame2	= new TreeMenu();
var branch2_1 = new TreeMenu();
stepFrame2.addItem(new TreeMenuItem("Branch2.1.&nbsp;","","","","Branch"));
branch2_1.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
branch2_1.addItem(new TreeMenuItem("2.1.1.&nbsp;New_Input user ID","s_1_0_0.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.2.&nbsp;New_Input Name","s_1_0_1.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.3.&nbsp;New_Input E-Mail","s_1_0_2.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.4.&nbsp;New_Clear Area(1)","s_1_0_3.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.5.&nbsp;New_Clear Area(2)","s_1_0_4.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.6.&nbsp;New_Select Workflow(1)","s_1_0_5.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.7.&nbsp;New_Select Workflow(2)","s_1_0_6.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.8.&nbsp;New_Search","s_1_0_7.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.9.&nbsp;New_Select a user ID","s_1_0_8.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.10.&nbsp;New_Send announcement e-mail option","s_1_0_9.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.11.&nbsp;New_Select a Indicate the Language to be Printed","s_1_0_10.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.12.&nbsp;New_Select add workflow(1)","s_1_0_11.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.13.&nbsp;New_Select add workflow(2)","s_1_0_12.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.14.&nbsp;New_Select add workflow","s_1_0_13.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.15.&nbsp;New_Select In Charge","s_1_0_14.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.16.&nbsp;New_Register","s_1_0_15.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.17.&nbsp;End","s_1_0_16.htm","course"));
stepFrame2.items[0].makeSubmenu(branch2_1);
treeMenu.items[2].makeSubmenu(stepFrame2);
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Input Name","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Input E-mail","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Select Area(1)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Select Area(2)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Select Workflow(1)","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Select Workflow(2)","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;Select Records(1)","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;Select Records(2)","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;Click Search","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;Select User ID","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;Select a send announcement mail","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;Select a Indicate the Language to be Printed","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;Select add workflow(1)","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;Select add workflow(2)","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;Add Workflow","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;Set initially displayed workflow","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;Select Person In Charge","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;Register","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;End","s_20.htm","course"));
