var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;転送先部門選択①","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;転送先部門選択②","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;担当者選択_入力／検索","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;担当者選択①","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;担当者選択②","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;転送先コメント入力","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;転送実行","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;終了","s_7.htm","course"));
