var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Approval of Assessment)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select the Number of Records(1)","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Select the Number of Records(2)","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Select Approval Method","s_3.htm","course"));
var stepFrame4	= new TreeMenu();
var branch4_1 = new TreeMenu();
stepFrame4.addItem(new TreeMenuItem("Branch4.1.&nbsp;","","","","Branch"));
branch4_1.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
branch4_1.addItem(new TreeMenuItem("4.1.1.&nbsp;Collective Approval","s_3_0_0.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.2.&nbsp;Individual Approval","s_3_0_1.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.3.&nbsp;End","s_3_0_2.htm","course"));
stepFrame4.items[0].makeSubmenu(branch4_1);
treeMenu.items[4].makeSubmenu(stepFrame4);
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Select Summary of Business Tab","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Select Judgment of the Customer/Credit Category Tab","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Select Calculation of Reserves Tab","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Select Credit List Tab","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;Select Retention Against Debtor Tab","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;Inquiry for Attachments","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;Inquiry for the Details of Attachments","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;Approval","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;End","s_12.htm","course"));
