var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Assessment Results Inquiry)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select Assessment/Judgment","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Search Assessment_Input the period of Assessing Period","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Search Assessment_Selection of the quarter month(1)","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Search Assessment_Selection of the quarter month(2)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Search Assessment_Input targeted year","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Search Assessment_Input Cust.Code","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Search Assessment_Input DUNS No.","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;Search Assessment_Input Cust. Name","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;Search Assessment_Selection of Country(1)","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;Search Assessment_Selection of Country(2)","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;Search Assessment_selection of the reason for identification(1)","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;Search Assessment_selection of the reason for identification(2)","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;Search Assessment_Selection of Credit Category(1)","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;Search Assessment_Selection of Credit Category(2)","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;Search Assessment_Credit category(1)","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;Search Assessment_Credit category(2)","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;Search Assessment_Co.(1)","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;Search Assessment_Co.(2)","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;Search Assessment_division(1)","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;Search Assessment_division(2)","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;Search Assessment_division(1)","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp;Search Assessment_division(2)","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;Search Assessment_affiliate company","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;Search Assessment_Input the date of starting process","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;Search Assessment_Input the date of ending process.","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;Search Assessment_Sort items(1)","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;Search Assessment_Sort items(2)","s_27.htm","course"));
treeMenu.addItem(new TreeMenuItem("29.&nbsp;Search Assessment_Sort order(1)","s_28.htm","course"));
treeMenu.addItem(new TreeMenuItem("30.&nbsp;Search Assessment_Sort order(2)","s_29.htm","course"));
treeMenu.addItem(new TreeMenuItem("31.&nbsp;Search Assessment_display the number of items(1)","s_30.htm","course"));
treeMenu.addItem(new TreeMenuItem("32.&nbsp;Search Assessment_display the number of items(2)","s_31.htm","course"));
treeMenu.addItem(new TreeMenuItem("33.&nbsp;Search Assessment_perform search","s_32.htm","course"));
treeMenu.addItem(new TreeMenuItem("34.&nbsp;Search Assessment_Moving to the screen of details","s_33.htm","course"));
treeMenu.addItem(new TreeMenuItem("35.&nbsp;Search Assessment_Select phase(1)","s_34.htm","course"));
treeMenu.addItem(new TreeMenuItem("36.&nbsp;Search Assessment_Select phase(2)","s_35.htm","course"));
treeMenu.addItem(new TreeMenuItem("37.&nbsp;Search Assessment_Summary of Business","s_36.htm","course"));
treeMenu.addItem(new TreeMenuItem("38.&nbsp;Search Assessment_Judgment of the Customer/Credit Category","s_37.htm","course"));
treeMenu.addItem(new TreeMenuItem("39.&nbsp;Search Assessment_Calculation of Reserves","s_38.htm","course"));
treeMenu.addItem(new TreeMenuItem("40.&nbsp;Search Assessment_Credit List","s_39.htm","course"));
treeMenu.addItem(new TreeMenuItem("41.&nbsp;Search Assessment_Retention against Debtor","s_40.htm","course"));
treeMenu.addItem(new TreeMenuItem("42.&nbsp;Search Assessment_Show Attachments","s_41.htm","course"));
treeMenu.addItem(new TreeMenuItem("43.&nbsp;Search Assessment_Inquiry for attachment file","s_42.htm","course"));
treeMenu.addItem(new TreeMenuItem("44.&nbsp;Search Assessment_moving to the screen of order","s_43.htm","course"));
treeMenu.addItem(new TreeMenuItem("45.&nbsp;Search Judgments of Overdue_the period of Assessing Period","s_44.htm","course"));
treeMenu.addItem(new TreeMenuItem("46.&nbsp;Search Judgments of Overdue_targeted year and months","s_45.htm","course"));
treeMenu.addItem(new TreeMenuItem("47.&nbsp;Search Judgments of Overdue_Input Cust.Code","s_46.htm","course"));
treeMenu.addItem(new TreeMenuItem("48.&nbsp;Search Judgments of Overdue_Input DUNS No.","s_47.htm","course"));
treeMenu.addItem(new TreeMenuItem("49.&nbsp;Search Judgments of Overdue_Input Cust.Name","s_48.htm","course"));
treeMenu.addItem(new TreeMenuItem("50.&nbsp;Search Judgments of Overdue_Selecting Country(1)","s_49.htm","course"));
treeMenu.addItem(new TreeMenuItem("51.&nbsp;Search Judgments of Overdue_Selecting Country(2)","s_50.htm","course"));
treeMenu.addItem(new TreeMenuItem("52.&nbsp;Search Judgments of Overdue_Selecting Area(1)","s_51.htm","course"));
treeMenu.addItem(new TreeMenuItem("53.&nbsp;Search Judgments of Overdue_Selecting Area(2)","s_52.htm","course"));
treeMenu.addItem(new TreeMenuItem("54.&nbsp;Search Judgments of Overdue_Selecting Co.(1)","s_53.htm","course"));
treeMenu.addItem(new TreeMenuItem("55.&nbsp;Search Judgments of Overdue_Selecting Co.(2)","s_54.htm","course"));
treeMenu.addItem(new TreeMenuItem("56.&nbsp;Search Judgments of Overdue_Selecting Cell(1)","s_55.htm","course"));
treeMenu.addItem(new TreeMenuItem("57.&nbsp;Search Judgments of Overdue_Selecting Cell(2)","s_56.htm","course"));
treeMenu.addItem(new TreeMenuItem("58.&nbsp;Search Judgments of Overdue_Related Parties","s_57.htm","course"));
treeMenu.addItem(new TreeMenuItem("59.&nbsp;Search Judgments of Overdue_Input Due Date From","s_58.htm","course"));
treeMenu.addItem(new TreeMenuItem("60.&nbsp;Search Judgments of Overdue_Input Due Date To","s_59.htm","course"));
treeMenu.addItem(new TreeMenuItem("61.&nbsp;Search Judgments of Overdue_Sort items(1)","s_60.htm","course"));
treeMenu.addItem(new TreeMenuItem("62.&nbsp;Search Judgments of Overdue_Sort items(2)","s_61.htm","course"));
treeMenu.addItem(new TreeMenuItem("63.&nbsp;Search Judgments of Overdue_Sort order(1)","s_62.htm","course"));
treeMenu.addItem(new TreeMenuItem("64.&nbsp;Search Judgments of Overdue_order(2)","s_63.htm","course"));
treeMenu.addItem(new TreeMenuItem("65.&nbsp;Search Judgments of Overdue_the number of display(1)","s_64.htm","course"));
treeMenu.addItem(new TreeMenuItem("66.&nbsp;Search Judgments of Overdue_the number of display(2)","s_65.htm","course"));
treeMenu.addItem(new TreeMenuItem("67.&nbsp;Search Judgments of Overdue_Searching","s_66.htm","course"));
treeMenu.addItem(new TreeMenuItem("68.&nbsp;Search Judgments of Overdue_move to the screen of detail","s_67.htm","course"));
treeMenu.addItem(new TreeMenuItem("69.&nbsp;Search Judgments of Overdue_Selecting the phase(1)","s_68.htm","course"));
treeMenu.addItem(new TreeMenuItem("70.&nbsp;Search Judgments of Overdue_Selecting the phase(2)","s_69.htm","course"));
treeMenu.addItem(new TreeMenuItem("71.&nbsp;Search Judgments of Overdue_the number of details(1)","s_70.htm","course"));
treeMenu.addItem(new TreeMenuItem("72.&nbsp;Search Judgments of Overdue_the number of details(2)","s_71.htm","course"));
treeMenu.addItem(new TreeMenuItem("73.&nbsp;Search Judgments of Overdue_Show Attachments in detail","s_72.htm","course"));
treeMenu.addItem(new TreeMenuItem("74.&nbsp;Search Judgments of Overdue_Inquiry for attachment file","s_73.htm","course"));
treeMenu.addItem(new TreeMenuItem("75.&nbsp;Search Judgments of Overdue_Show Attachments","s_74.htm","course"));
treeMenu.addItem(new TreeMenuItem("76.&nbsp;Search Judgments of Overdue_the screen of Inquiry for attachment file","s_75.htm","course"));
treeMenu.addItem(new TreeMenuItem("77.&nbsp;Search Judgments of Overdue_Assessment Results Inquiry","s_76.htm","course"));
treeMenu.addItem(new TreeMenuItem("78.&nbsp;End","s_77.htm","course"));
