var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Approval of Judgement)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Selection Records of Approval Waiting List(1)","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Selection Records of Approval Waiting List(2)","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Selection Targeted Approval","s_3.htm","course"));
var stepFrame4	= new TreeMenu();
var branch4_1 = new TreeMenu();
stepFrame4.addItem(new TreeMenuItem("Branch4.1.&nbsp;","","","","Branch"));
branch4_1.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
branch4_1.addItem(new TreeMenuItem("4.1.1.&nbsp;Operation Batch Approval","s_3_0_0.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.2.&nbsp;Operation approval individually","s_3_0_1.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.3.&nbsp;End","s_3_0_2.htm","course"));
stepFrame4.items[0].makeSubmenu(branch4_1);
treeMenu.items[4].makeSubmenu(stepFrame4);
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Selection Records of description(1)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Selection Records of description(2)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Show Attachments","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Refference of Attachments","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;Operation Approval","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;End","s_9.htm","course"));
