var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Select Customer)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select Target","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Check to Take the Asssessment","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Select Customer_Show Comment(1)","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Select Customer_Show Comment(2)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Select Customer_Selection of The Authorizer(1)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Select Customer_Selection of The Authorizer(2)","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Select Customer_to input annulment and added comment","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;Select Customer_Selection of the tab of basic information","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;Select Customer_Selection of the tab of credit list","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;Select Customer_Selection Records of description(1)","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;Select Customer_Selection Records of description(2)","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;Select Customer_Select Customer registration","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;Targeted addition_selecction for assessing period(1)","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;Targeted addition_selecction for assessing period(2)","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;Targeted addtion_to input the A/C CD","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;Targetd addition_to input A/C name","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;Targeted selection_to select the company(1)","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;Targeted selection_to select the company(2)","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;Targeted selection_to select the number of indicated item(1)","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;Targeted selection_to select the number of indicated item(2)","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;Targeted addition_to operate search","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp;Targeted addition_to select A/C CD","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;Targeted addition_to select the reason for identification(1)","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;Targeted addition_to select the reason for identification(2)","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;Targeted addition_to select the person in charge for approval(1)","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;Targeted addition_to select the person in charge for approval(2)","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;Targeted addition_to input annulment and added comment","s_27.htm","course"));
treeMenu.addItem(new TreeMenuItem("29.&nbsp;Targeted addition_tab of basic information","s_28.htm","course"));
treeMenu.addItem(new TreeMenuItem("30.&nbsp;Targeted addition_tab of account of credit type","s_29.htm","course"));
treeMenu.addItem(new TreeMenuItem("31.&nbsp;Targeted addition_to operate addition","s_30.htm","course"));
treeMenu.addItem(new TreeMenuItem("32.&nbsp;End","s_31.htm","course"));
