var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Confirmation of Reserves)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select Cust Code","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Confirm Take","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Select Customer category(1)","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Select Customer category(2)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Select Credit category(1)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Select Credit category(2)","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Select Details of Reserves(1)","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;Select Details of Reserves(2)","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;Input Verification of judgment category","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;Select the Authorizer(1)","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;Select the Authorizer(2)","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;Registration","s_12.htm","course"));
var stepFrame13	= new TreeMenu();
var branch13_1 = new TreeMenu();
stepFrame13.addItem(new TreeMenuItem("Branch13.1.&nbsp;","","","","Branch"));
branch13_1.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
branch13_1.addItem(new TreeMenuItem("13.1.1.&nbsp;Result of assessment_ Select the phase(1)","s_12_0_0.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.2.&nbsp;Result of assessment_ Select the phase(2)","s_12_0_1.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.3.&nbsp;Result of assessment_Select the summary of Business tab ","s_12_0_2.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.4.&nbsp;Result of assessment_Select Judgment of the Customer/Credit Category tab","s_12_0_3.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.5.&nbsp;Result of assessment_Select Calculation of Reserve tab","s_12_0_4.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.6.&nbsp;Result of assessment Select the Credit List tab","s_12_0_5.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.7.&nbsp;Result of assessment_Select Retention against Debtor tab","s_12_0_6.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.8.&nbsp;Result of assessment_refer to attachments","s_12_0_7.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.9.&nbsp;Result of assessment_inquiry for attachments","s_12_0_8.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.10.&nbsp;Result of assessment_Move to Confirmation of reserves page","s_12_0_9.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.11.&nbsp;End","s_12_0_10.htm","course"));
stepFrame13.items[0].makeSubmenu(branch13_1);
treeMenu.items[13].makeSubmenu(stepFrame13);
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;End","s_13.htm","course"));
