var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（クレーム債権再設定承認）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;表示件数選択①","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;表示件数選択②","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;勘定先CD選択","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;添付参照","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;添付内容照会","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;承認実行","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;終了","s_7.htm","course"));
