var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（査定会社メンテナンス）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;査定会社一覧","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;新規登録_システム選択①","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;新規登録_システム選択②","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;新規登録_会社選択①","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;新規登録_会社選択②","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;新規登録_部門入力","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;新規登録_部門名称（日本語）入力","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;新規登録_部門名称（英語）入力","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;新規登録_標準時刻選択①","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;新規登録_標準時刻選択②","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;新規登録_抽出対象設定","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;新規登録_新規登録実行","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;訂正・削除_システム選択","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;訂正・削除_会社選択①","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;訂正・削除_会社選択②","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;訂正・削除_部門入力","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;訂正・削除_部門名称入力","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;訂正・削除_表示件数選択①","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;訂正・削除_表示件数選択②","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;訂正・削除_検索実行","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;訂正・削除_部門選択","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp;訂正・削除_削除実行","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;訂正・削除_部門名称（日本語）入力","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;訂正・削除_部門名称（英語）入力","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;訂正・削除_標準時刻選択①","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;訂正・削除_標準時刻選択②","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;訂正・削除_抽出対象選択","s_27.htm","course"));
treeMenu.addItem(new TreeMenuItem("29.&nbsp;訂正・削除_登録実行","s_28.htm","course"));
treeMenu.addItem(new TreeMenuItem("30.&nbsp;終了","s_29.htm","course"));
