var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;選定対象選択","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;もぎ取り確認","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;対象先選定_コメント表示①","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;対象先選定_コメント表示②","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;対象先選定_承認担当者選択①","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;対象先選定_承認担当者選択②","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;対象先選定_対象外・追加コメント入力","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;対象先選定_基本情報タブ選択","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;対象先選定_債権明細タブ選択","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;対象先選定_明細表示件数選択①","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;対象先選定_明細表示件数選択②","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;対象先選定_対象先選定登録実行","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;追加対象先_査定期選択①","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;追加対象先_査定期選択②","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;追加対象先_勘定先CD入力","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;追加対象先_勘定先名称入力","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;対象先選定_会社選択①","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;対象先選定_会社選択②","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;追加対象先_表示件数選択①","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;追加対象先_表示件数選択②","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;追加対象先_検索実行","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp;追加対象先_勘定先CD選択","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;追加対象先_抽出事由選択①","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;追加対象先_抽出事由選択②","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;追加対象先_承認担当者選択①","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;追加対象先_承認担当者選択②","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;追加対象先_対象外・追加コメント入力","s_27.htm","course"));
treeMenu.addItem(new TreeMenuItem("29.&nbsp;追加対象先_基本情報タブ","s_28.htm","course"));
treeMenu.addItem(new TreeMenuItem("30.&nbsp;追加対象先_債権明細タブ","s_29.htm","course"));
treeMenu.addItem(new TreeMenuItem("31.&nbsp;追加対象先_追加実行","s_30.htm","course"));
treeMenu.addItem(new TreeMenuItem("32.&nbsp;終了","s_31.htm","course"));
