#------------------------------------------------------------------------
#	FTPサーバー接続情報
#	省略時：例外発生
#------------------------------------------------------------------------
ftp.host = 172.25.65.68
ftp.user = asset_docs
ftp.pass = asset_docs
ftp.dir = doc
ftp.dirHelp = help

#------------------------------------------------------------------------
#	SMTPサーバー接続情報
#	省略時：例外発生
#------------------------------------------------------------------------
smtp.host = hostname
smtp.from = abc@abc.com
#メール送信実行有無
smtp.enabled = false
#smtp.enabled = true

#------------------------------------------------------------------------
#	ログレベル
#	0～ログレベルまでを出力
#	0:エラー 1:警告 2:情報 3:デバッグ
#	省略時：0
#------------------------------------------------------------------------
log.level = 3

#------------------------------------------------------------------------
#	セッションタイムアウト値（秒）
#	省略時：86400
#------------------------------------------------------------------------
session.timeout = 3600

#------------------------------------------------------------------------
#	アップロードファイルの最大サイズ
#	単位：ＭＢ
#	省略時：２ＭＢ
#------------------------------------------------------------------------
#upload.maxsize = 4

#------------------------------------------------------------------------
#	JDBC接続情報
#
#	接続先ＵＲＬ
#		接続先が
#  	    	HOST				127.0.0.1
#　	　　	SID				TEST
#   	    PORT				1521
#		の場合、
#			接続先ＵＲＬ　jdbc:oracle:thin:@127.0.0.1:1521:TEST
#
#	キー ：ルートディレクトリ．ＵＲＬ　 未定義の場合はデフォルト(db.URL)を使用する。
#		db.URL				http://host/xxx    --> /xxx/jservlet  開発
#------------------------------------------------------------------------
#JDBCドライバ名
db.Name = oracle.jdbc.driver.OracleDriver
#接続先ＵＲＬ
db.URL = jdbc:oracle:thin:@172.20.108.196:1521:SJAST
#ユーザー
db.User = sjast
#パスワード
db.Password = sjast
#リトライ回数（10デフォ）
db.Timeout = 10
#最大プールコネクション数
db.MaxConn = 20

#------------------------------------------------------------------------
#	InfoDirectoryプロパティ
#------------------------------------------------------------------------
# InfoDirectory接続情報
INFOD.FACTORY = com.sun.jndi.ldap.LdapCtxFactory
INFOD.URL = ldap://sinldapv01.in.sojitz.com:389
INFOD.AUTH = simple
INFOD.REFER = follow
# 検索ユーザ接続情報
INFOD.SEARCHUSER.DN = uid=group,o=admin,l=admin,c=jp
INFOD.SEARCHUSER.PASSWORD = group
# 検索ベース(日本語用、英語用）
INFOD.SEARCHBASE.JP = l=japan,c=jp
INFOD.SEARCHBASE.EN = l=world,c=jp
# InfoDirectory認証有無
INFOD.ENABLED = false

#------------------------------------------------------------------------
#	SSOプロパティ
#	true：ログイン画面非表示 false：ログイン画面表示
#	省略時：true
#------------------------------------------------------------------------
SSO.LOGIN = true

