var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Registration of Assessment)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select the A/C for Assessment","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Veryfy Taking","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Input the Description of Business","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Input the Shareholder's Name","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Input the Number of Shares","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Input the Share Holding Ratio","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Input the Financial Condition","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;move to the Customer/Credit Category of Judgment screen","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;Select Customer Category","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;Normal Customer/Customer Requiring Caution_select appropriate reasons","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;Normal Customer/Customer Requiring Caution_input the grounds for the Judgment","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;Normal Customer/Customer Requiring Caution_input Reasons for the Judgment","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;Normal Customer/Customer Requiring Caution_input Key Events","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;go to the Judgment of Reserves screen","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;Customer with Doubtful Debts_Selection the appropriate reason","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;Customer with Doubtful Debts_Select appropriate reasons","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;Customer with Doubtful Debts_input Reasons for the Judgment of [Credit Category]","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;Customer with Doubtful Debts_input Key Events","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;go to the Judgment of Reserves screen","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;Bankruptcy or Rehabilitation_Select appropriate reasons","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;Bankruptcy or Rehabilitation_Input the reason for the judgment.","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp;Bankruptcy or Rehabilitation_input the Reason for the Judgment","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;Bankruptcy or Rehabilitation_input Key Events of [Credit Category]","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;go to the Judgment of Reserves screen","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;Normal Debt_delineation","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;Normal Debt_scroll down","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;Normal Debt_Set 1st/3rd quarter Flag","s_27.htm","course"));
var stepFrame28	= new TreeMenu();
var branch28_1 = new TreeMenu();
stepFrame28.addItem(new TreeMenuItem("Branch28.1.&nbsp;","","","","Branch"));
branch28_1.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
branch28_1.addItem(new TreeMenuItem("28.1.1.&nbsp;Normal Debte_Select Flag Grouping (1)","s_27_0_0.htm","course"));
branch28_1.addItem(new TreeMenuItem("28.1.2.&nbsp;Normal Debt_Select Flag Grouping (2)","s_27_0_1.htm","course"));
branch28_1.addItem(new TreeMenuItem("28.1.3.&nbsp;Normal Debt_ Input Flag Comment","s_27_0_2.htm","course"));
branch28_1.addItem(new TreeMenuItem("28.1.4.&nbsp;Normal Debt_end of 1st/3rd quarter Flag settings","s_27_0_3.htm","course"));
branch28_1.addItem(new TreeMenuItem("28.1.5.&nbsp;End","s_27_0_4.htm","course"));
stepFrame28.items[0].makeSubmenu(branch28_1);
treeMenu.items[28].makeSubmenu(stepFrame28);
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("29.&nbsp;Normal Debt_Selection of The Authorizer(1)","s_28.htm","course"));
treeMenu.addItem(new TreeMenuItem("30.&nbsp;Normal Debt_Selection of The Authorizer(2)","s_29.htm","course"));
treeMenu.addItem(new TreeMenuItem("31.&nbsp;Normal Debt_Register assessment","s_30.htm","course"));
treeMenu.addItem(new TreeMenuItem("32.&nbsp;Except of normal debt_description of outline","s_31.htm","course"));
treeMenu.addItem(new TreeMenuItem("33.&nbsp;Not normal debt_Input A/C CD","s_32.htm","course"));
treeMenu.addItem(new TreeMenuItem("34.&nbsp;Not normal debt_Input customer name ","s_33.htm","course"));
treeMenu.addItem(new TreeMenuItem("35.&nbsp;Not normal debt_Input A/C CD","s_34.htm","course"));
treeMenu.addItem(new TreeMenuItem("36.&nbsp;Not normal debt_Input amount of money","s_35.htm","course"));
treeMenu.addItem(new TreeMenuItem("37.&nbsp;Not normal debt_Confirm automatic reflection of amount ","s_36.htm","course"));
treeMenu.addItem(new TreeMenuItem("38.&nbsp;Not normal debt_Input Contract amount of real property　","s_37.htm","course"));
treeMenu.addItem(new TreeMenuItem("39.&nbsp;Not normal debt_Input Estimated amount of real property","s_38.htm","course"));
treeMenu.addItem(new TreeMenuItem("40.&nbsp;Not normal debt_Input Contract amount of personal property","s_39.htm","course"));
treeMenu.addItem(new TreeMenuItem("41.&nbsp;Not normal debt_Input Estimated amount of personal property","s_40.htm","course"));
treeMenu.addItem(new TreeMenuItem("42.&nbsp;Not normal debt_Input Contract amount of trade insurance","s_41.htm","course"));
treeMenu.addItem(new TreeMenuItem("43.&nbsp;Not normal debt_Input Estimated amount of trade insurance","s_42.htm","course"));
treeMenu.addItem(new TreeMenuItem("44.&nbsp;Not normal debt_Input other Contract amount ","s_43.htm","course"));
treeMenu.addItem(new TreeMenuItem("45.&nbsp;Not normal debt_Input other Estimated amount ","s_44.htm","course"));
treeMenu.addItem(new TreeMenuItem("46.&nbsp;Not normal debt_Confirm automatic reflection of Estimated amount","s_45.htm","course"));
treeMenu.addItem(new TreeMenuItem("47.&nbsp;Not normal debt_Input Retention against Debtor","s_46.htm","course"));
treeMenu.addItem(new TreeMenuItem("48.&nbsp;Not normal debt_Input Retention against Third-party ","s_47.htm","course"));
treeMenu.addItem(new TreeMenuItem("49.&nbsp;Not normal debt_Input Details of Security(3)","s_48.htm","course"));
treeMenu.addItem(new TreeMenuItem("50.&nbsp;Not normal debt_Input Details of Other Collectable Amount(4)","s_49.htm","course"));
treeMenu.addItem(new TreeMenuItem("51.&nbsp;Not normal debt_Input Amount for probable recourse(5)","s_50.htm","course"));
treeMenu.addItem(new TreeMenuItem("52.&nbsp;Not normal debt_Input Additional Amount of Reserves","s_51.htm","course"));
treeMenu.addItem(new TreeMenuItem("53.&nbsp;Not normal debt_Input Details of Other","s_52.htm","course"));
treeMenu.addItem(new TreeMenuItem("54.&nbsp;Not normal debt_Input Details of Other Collectable Amount","s_53.htm","course"));
treeMenu.addItem(new TreeMenuItem("55.&nbsp;Not normal debt_Input Details of Amount for probable recourse","s_54.htm","course"));
treeMenu.addItem(new TreeMenuItem("56.&nbsp;Not normal debt_Input Grounds for Calculation of Reserves","s_55.htm","course"));
treeMenu.addItem(new TreeMenuItem("57.&nbsp;Not normal debt_Input Estimated Recoverable Amount","s_56.htm","course"));
treeMenu.addItem(new TreeMenuItem("58.&nbsp;Not normal debt_Set 1st/3rd quarter Flag","s_57.htm","course"));
var stepFrame58	= new TreeMenu();
var branch58_1 = new TreeMenu();
stepFrame58.addItem(new TreeMenuItem("Branch58.1.&nbsp;","","","","Branch"));
branch58_1.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
branch58_1.addItem(new TreeMenuItem("58.1.1.&nbsp;Not normal debt_Select Flag Grouping (1)","s_57_0_0.htm","course"));
branch58_1.addItem(new TreeMenuItem("58.1.2.&nbsp;Not normal debt_Select Flag Grouping (2)","s_57_0_1.htm","course"));
branch58_1.addItem(new TreeMenuItem("58.1.3.&nbsp;Not normal debt_Input Flag comment","s_57_0_2.htm","course"));
branch58_1.addItem(new TreeMenuItem("58.1.4.&nbsp;Not normal debt_finish confirmation of 1st/3rd quarter Flag  ","s_57_0_3.htm","course"));
branch58_1.addItem(new TreeMenuItem("58.1.5.&nbsp;End","s_57_0_4.htm","course"));
stepFrame58.items[0].makeSubmenu(branch58_1);
treeMenu.items[59].makeSubmenu(stepFrame58);
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("59.&nbsp;Not normal debt_Select Authorizer(1)","s_58.htm","course"));
treeMenu.addItem(new TreeMenuItem("60.&nbsp;Not normal debt_Select Authorizer(2)","s_59.htm","course"));
treeMenu.addItem(new TreeMenuItem("61.&nbsp;Not normal debt_Register Assessment","s_60.htm","course"));
treeMenu.addItem(new TreeMenuItem("62.&nbsp;End","s_61.htm","course"));
