var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Workflow Maintenance)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;List of Workflow","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Select System(1)","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Select System(2)","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Select Co.(1)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;.Select Co(2)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Input Workflow Name(Japanese)","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Input Workflow Name(English)","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;[Judgment on Overdue] set privilege items","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;[Judgment on Overdue] select next phase(1)","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;[Judgment on Overdue] select next phase(2)","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;[Judgment on Overdue] select return route","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;[Assessment] set privilege items","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;[Assessment] select next phase(1)","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;[Assessment] select next phase(2)","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;[Assessment] set returnability","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;[Reserve Verification/Confirmation] select provilege items","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;[Reserve Verification/Confirmation] select next phase(1)","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;[Reserve Verification/Confirmation] select next phase(2)","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;[System Management] select privilege items","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;[Reserve Verification/Confirmation] select next phase(1)","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;[Reserve Verification/Confirmation] select next phase(2)","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp; Select System Manager Category","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;Registration","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;modify or delete_select system","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;modify or delete_select company(1)","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;modify or delete_select company(2)","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;modify or delete_input workflow pattern name","s_27.htm","course"));
treeMenu.addItem(new TreeMenuItem("29.&nbsp;modify or delete_set number of items displayed(1)","s_28.htm","course"));
treeMenu.addItem(new TreeMenuItem("30.&nbsp;modify or delete_set number of items displayed(2)","s_29.htm","course"));
treeMenu.addItem(new TreeMenuItem("31.&nbsp;modify or delete_search","s_30.htm","course"));
treeMenu.addItem(new TreeMenuItem("32.&nbsp;modify or delete_select pattern ID","s_31.htm","course"));
treeMenu.addItem(new TreeMenuItem("33.&nbsp;modify or delete_registration","s_32.htm","course"));
treeMenu.addItem(new TreeMenuItem("34.&nbsp;End","s_33.htm","course"));
