var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（査定内容照会）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;査定／滞留判定選択","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;査定検索_査定期入力","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;査定検索_四半期区分選択①","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;査定検索_四半期区分選択②","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;査定検索_対象年月入力","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;査定検索_勘定先CD入力","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;査定検索_DUNS No.入力","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;査定検索_勘定先名称入力","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;査定検索_所在国選択①","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;査定検索_所在国選択②","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;査定検索_抽出事由選択①","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;査定検索_抽出事由選択②","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;査定検索_取引先区分選択①","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;査定検索_取引先区分選択②","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;査定検索__債権区分選択①","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;査定検索__債権区分選択②","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;査定検索_査定会社選択①","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;査定検索_査定会社選択②","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;査定検索_部門選択①","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;査定検索_部門選択②","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;査定検索_部選択①","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp;査定検索_部選択②","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;査定検索_関係会社入力","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;査定検索_処理日From入力","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;査定検索_処理日To入力","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;査定検索_ソート項目選択①","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;査定検索_ソート項目選択②","s_27.htm","course"));
treeMenu.addItem(new TreeMenuItem("29.&nbsp;査定検索_ソート順選択①","s_28.htm","course"));
treeMenu.addItem(new TreeMenuItem("30.&nbsp;査定検索_ソート順選択②","s_29.htm","course"));
treeMenu.addItem(new TreeMenuItem("31.&nbsp;査定検索_表示件数選択①","s_30.htm","course"));
treeMenu.addItem(new TreeMenuItem("32.&nbsp;査定検索_表示件数選択②","s_31.htm","course"));
treeMenu.addItem(new TreeMenuItem("33.&nbsp;査定検索_検索実行","s_32.htm","course"));
treeMenu.addItem(new TreeMenuItem("34.&nbsp;査定検索_詳細画面へ遷移","s_33.htm","course"));
treeMenu.addItem(new TreeMenuItem("35.&nbsp;査定検索_フェーズ選択①","s_34.htm","course"));
treeMenu.addItem(new TreeMenuItem("36.&nbsp;査定検索_フェーズ選択②","s_35.htm","course"));
treeMenu.addItem(new TreeMenuItem("37.&nbsp;査定検索_取引先概要タブ選択","s_36.htm","course"));
treeMenu.addItem(new TreeMenuItem("38.&nbsp;査定検索_取引先・債権区分判定タブ選択","s_37.htm","course"));
treeMenu.addItem(new TreeMenuItem("39.&nbsp;査定検索_引当金判定タブ選択","s_38.htm","course"));
treeMenu.addItem(new TreeMenuItem("40.&nbsp;査定検索_債権明細タブ選択","s_39.htm","course"));
treeMenu.addItem(new TreeMenuItem("41.&nbsp;査定検索_留保債務タブ選択","s_40.htm","course"));
treeMenu.addItem(new TreeMenuItem("42.&nbsp;査定検索_添付参照","s_41.htm","course"));
treeMenu.addItem(new TreeMenuItem("43.&nbsp;査定検索_添付内容照会","s_42.htm","course"));
treeMenu.addItem(new TreeMenuItem("44.&nbsp;査定検索_債権査定内容照会画面へ遷移","s_43.htm","course"));
treeMenu.addItem(new TreeMenuItem("45.&nbsp;滞留判定検索_査定期入力","s_44.htm","course"));
treeMenu.addItem(new TreeMenuItem("46.&nbsp;滞留判定検索_対象年月","s_45.htm","course"));
treeMenu.addItem(new TreeMenuItem("47.&nbsp;滞留判定検索_勘定先CD入力","s_46.htm","course"));
treeMenu.addItem(new TreeMenuItem("48.&nbsp;滞留判定検索_DUNS No.入力","s_47.htm","course"));
treeMenu.addItem(new TreeMenuItem("49.&nbsp;滞留判定検索_勘定先名称入力","s_48.htm","course"));
treeMenu.addItem(new TreeMenuItem("50.&nbsp;滞留判定検索_所在国選択①","s_49.htm","course"));
treeMenu.addItem(new TreeMenuItem("51.&nbsp;滞留判定検索_所在国選択②","s_50.htm","course"));
treeMenu.addItem(new TreeMenuItem("52.&nbsp;滞留判定検索_査定会社選択①","s_51.htm","course"));
treeMenu.addItem(new TreeMenuItem("53.&nbsp;滞留判定検索_査定会社選択②","s_52.htm","course"));
treeMenu.addItem(new TreeMenuItem("54.&nbsp;滞留判定検索_部門選択①","s_53.htm","course"));
treeMenu.addItem(new TreeMenuItem("55.&nbsp;滞留判定検索_部門選択②","s_54.htm","course"));
treeMenu.addItem(new TreeMenuItem("56.&nbsp;滞留判定検索_部選択①","s_55.htm","course"));
treeMenu.addItem(new TreeMenuItem("57.&nbsp;滞留判定検索_部選択②","s_56.htm","course"));
treeMenu.addItem(new TreeMenuItem("58.&nbsp;滞留判定検索_関係者入力","s_57.htm","course"));
treeMenu.addItem(new TreeMenuItem("59.&nbsp;滞留判定検索_処理日From入力","s_58.htm","course"));
treeMenu.addItem(new TreeMenuItem("60.&nbsp;滞留判定検索_処理日To入力","s_59.htm","course"));
treeMenu.addItem(new TreeMenuItem("61.&nbsp;滞留判定検索_ソート項目選択①","s_60.htm","course"));
treeMenu.addItem(new TreeMenuItem("62.&nbsp;滞留判定検索_ソート項目選択②","s_61.htm","course"));
treeMenu.addItem(new TreeMenuItem("63.&nbsp;滞留判定検索_ソート順選択①","s_62.htm","course"));
treeMenu.addItem(new TreeMenuItem("64.&nbsp;滞留判定検索_ソート順選択②","s_63.htm","course"));
treeMenu.addItem(new TreeMenuItem("65.&nbsp;滞留判定検索_表示件数選択①","s_64.htm","course"));
treeMenu.addItem(new TreeMenuItem("66.&nbsp;滞留判定検索_表示件数選択②","s_65.htm","course"));
treeMenu.addItem(new TreeMenuItem("67.&nbsp;滞留判定検索_検索実行","s_66.htm","course"));
treeMenu.addItem(new TreeMenuItem("68.&nbsp;滞留判定検索_詳細画面へ遷移","s_67.htm","course"));
treeMenu.addItem(new TreeMenuItem("69.&nbsp;滞留判定検索_フェーズ選択①","s_68.htm","course"));
treeMenu.addItem(new TreeMenuItem("70.&nbsp;滞留判定検索\\フェーズ選択②","s_69.htm","course"));
treeMenu.addItem(new TreeMenuItem("71.&nbsp;滞留判定検索_明細表示件数選択①","s_70.htm","course"));
treeMenu.addItem(new TreeMenuItem("72.&nbsp;滞留判定検索_明細表示件数選択②","s_71.htm","course"));
treeMenu.addItem(new TreeMenuItem("73.&nbsp;滞留判定検索_明細添付参照","s_72.htm","course"));
treeMenu.addItem(new TreeMenuItem("74.&nbsp;滞留判定検索_明細添付内容照会画面","s_73.htm","course"));
treeMenu.addItem(new TreeMenuItem("75.&nbsp;滞留判定検索_添付参照","s_74.htm","course"));
treeMenu.addItem(new TreeMenuItem("76.&nbsp;滞留判定検索_添付内容照会画面","s_75.htm","course"));
treeMenu.addItem(new TreeMenuItem("77.&nbsp;滞留判定検索_債権査定内容照会画面へ遷移","s_76.htm","course"));
treeMenu.addItem(new TreeMenuItem("78.&nbsp;終了","s_77.htm","course"));
