var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;一覧表示件数選択①","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;一覧表示件数選択②","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;承認対象選択","s_3.htm","course"));
var stepFrame4	= new TreeMenu();
var branch4_1 = new TreeMenu();
stepFrame4.addItem(new TreeMenuItem("ブランチ4.1.&nbsp;新規ブランチ","","","","Branch"));
branch4_1.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
branch4_1.addItem(new TreeMenuItem("4.1.1.&nbsp;一括承認実行","s_3_0_0.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.2.&nbsp;個別承認実行","s_3_0_1.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.3.&nbsp;終了","s_3_0_2.htm","course"));
stepFrame4.items[0].makeSubmenu(branch4_1);
treeMenu.items[4].makeSubmenu(stepFrame4);
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;添付参照","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;添付内容照会","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;承認実行","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;終了","s_7.htm","course"));
