var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Select the return category","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Assessment Phase_Input the return comment","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Assessment Phase_Select the return phase","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Assessment Phase_Returning","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;The return by office_Select the return type(1)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;The return by office__Select the return type(2)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;The return by office_The return comment","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;The return by office_Returning","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;Select the new return direction_Select the return phase(1)","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;Select the new return direction_Select the return phase(2)","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;Select the new return direction_Select Dept. for Returning(1)","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;Select the new return direction_Select Dept. for Returning(2)","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;Select the new return direction_input/search","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;Select the new return direction_select the person in charge(1)","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;Select the new return direction_select the person in charge(2)","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;Select the new return direction_Input Return comment","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;Select the new return direction_Returning","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;End","s_17.htm","course"));
