var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（業務フローパターンメンテナンス）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;業務フローパターン一覧","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;システム選択①","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;システム選択②","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;会社選択①","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;会社選択②","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;業務フローパターン名称（日本語）入力","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;業務フローパターン名称（英語）入力","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;[実質滞留債権判定]権限付与項目選択","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;[実質滞留債権判定]次フェーズ選択①","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;[実質滞留債権判定]次フェーズ選択②","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;[実質滞留債権判定]差戻経由選択","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;[査定]権限付与項目選択","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;[査定]次フェーズ選択①","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;[査定]次フェーズ選択②","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;[査定]差戻可否選択","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;[査定]二次査定区分選択①","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;[査定]二次査定区分選択②","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;[引当金検証/確認]権限付与項目選択","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;[引当金検証/確認]次フェーズ選択①","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;[引当金検証/確認]次フェーズ選択②","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;[システム管理]権限付与項目選択","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp;[引当金検証/確認]次フェーズ選択①","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;[引当金検証/確認]次フェーズ選択②","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;システム管理者専用区分選択","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;登録実行","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;訂正・削除時_システム選択","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;訂正・削除時_会社選択①","s_27.htm","course"));
treeMenu.addItem(new TreeMenuItem("29.&nbsp;訂正・削除時_会社選択②","s_28.htm","course"));
treeMenu.addItem(new TreeMenuItem("30.&nbsp;訂正・削除時_業務フローパターン名称入力","s_29.htm","course"));
treeMenu.addItem(new TreeMenuItem("31.&nbsp;訂正・削除時_表示件数選択①","s_30.htm","course"));
treeMenu.addItem(new TreeMenuItem("32.&nbsp;訂正・削除時_表示件数選択②","s_31.htm","course"));
treeMenu.addItem(new TreeMenuItem("33.&nbsp;訂正・削除時_検索実行","s_32.htm","course"));
treeMenu.addItem(new TreeMenuItem("34.&nbsp;訂正・削除時_パターンID選択","s_33.htm","course"));
treeMenu.addItem(new TreeMenuItem("35.&nbsp;訂正・削除時_登録実行","s_34.htm","course"));
treeMenu.addItem(new TreeMenuItem("36.&nbsp;終了","s_35.htm","course"));
