var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;差戻種類選択","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;査定フェーズ差戻_差戻コメント入力","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;査定フェーズ差戻_フェーズ選択","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;査定フェーズ差戻_差戻実行","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;事務局差戻_差戻区分選択①","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;事務局差戻_差戻区分選択②","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;事務局差戻_差戻コメント","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;事務局差戻_差戻実行","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;新規差戻先選択_差戻フェーズ選択①","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;新規差戻先選択_差戻フェーズ選択②","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;新規差戻先選択_差戻先部門選択①","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;新規差戻先選択_差戻先部門選択②","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;新規差戻先選択_入力／検索","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;新規差戻先選択_担当者選択①","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;新規差戻先選択_担当者選択②","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;新規差戻先選択_差戻コメント入力","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;新規差戻先選択_差戻実行","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;終了","s_17.htm","course"));
