var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（帳票ダウンロード）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;帳票種別選択①","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;帳票種別選択②","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;査定期入力","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;半期区分選択①","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;半期区分選択②","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;対象年月入力","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;勘定先CD入力","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;DUNS No.入力","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;勘定先名称入力","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;査定会社選択①","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;査定会社選択②","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;部門選択①","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;部門選択②","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;ダウンロード実行","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;ダウンロード確認","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;マクロ設定","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;終了","s_17.htm","course"));
