var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;業務フロー切替①","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;業務フロー切替②","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;査定期選択①","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;査定期選択②","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;対象年月①","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;対象年月②","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;代行画面切替選択①","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;代行画面切替選択②","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;終了","s_8.htm","course"));
