var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;ユーザID入力","s_1.htm","course"));
var stepFrame2	= new TreeMenu();
var branch2_1 = new TreeMenu();
stepFrame2.addItem(new TreeMenuItem("ブランチ2.1.&nbsp;新規ブランチ","","","","Branch"));
branch2_1.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
branch2_1.addItem(new TreeMenuItem("2.1.1.&nbsp;新規時_ユーザID入力","s_1_0_0.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.2.&nbsp;新規時_氏名入力","s_1_0_1.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.3.&nbsp;新規時_E-Mail入力","s_1_0_2.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.4.&nbsp;新規時_地域クリア①","s_1_0_3.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.5.&nbsp;新規時_地域クリア②","s_1_0_4.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.6.&nbsp;新規時_業務フロー選択①","s_1_0_5.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.7.&nbsp;新規時_業務フロー選択②","s_1_0_6.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.8.&nbsp;新規時_検索実行","s_1_0_7.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.9.&nbsp;新規時_ユーザID選択","s_1_0_8.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.10.&nbsp;新規時_メール配信選択","s_1_0_9.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.11.&nbsp;新規時_帳票出力言語選択","s_1_0_10.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.12.&nbsp;新規時_追加業務フローパターン選択①","s_1_0_11.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.13.&nbsp;新規時_追加業務フローパターン選択②","s_1_0_12.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.14.&nbsp;新規時_業務フローパターン追加","s_1_0_13.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.15.&nbsp;新規時_担当選択","s_1_0_14.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.16.&nbsp;新規時_登録実行","s_1_0_15.htm","course"));
branch2_1.addItem(new TreeMenuItem("2.1.17.&nbsp;終了","s_1_0_16.htm","course"));
stepFrame2.items[0].makeSubmenu(branch2_1);
treeMenu.items[2].makeSubmenu(stepFrame2);
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;氏名入力","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;E-Mail入力","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;地域選択①","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;地域選択②","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;業務フロー選択①","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;業務フロー選択②","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;表示件数選択①","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;表示件数選択②","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;検索実行","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;ユーザID選択","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;メール配信可否選択","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;帳票出力言語選択","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;追加業務フローパターン選択①","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;追加業務フローパターン選択②","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;業務フローパターン追加","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;既定表示内容選択","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;担当選択","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;登録実行","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;終了","s_20.htm","course"));
