var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（査定登録）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;査定対象の勘定先選択","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;もぎ取り確認","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;事業内容入力","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;株主名称入力","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;保有株数入力","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;保有率入力","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;決算概況入力","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;取引先・債権区分判定画面へ遷移","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;取引先区分の選択","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;正常先・要注意先_該当事由選択","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;正常先・要注意先_判定根拠入力","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;正常先・要注意先_判定事由入力","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;正常先・要注意先_発生経緯入力","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;引当金判定画面へ遷移","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;貸倒懸念先_該当事由選択","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;貸倒懸念先_判定根拠入力","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;貸倒懸念先_判定事由入力","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;貸倒懸念先_発生経緯入力","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;引当金判定画面へ遷移","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;破産更生先_該当事由選択","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;破産更生先_判定根拠入力","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp;破産更生先_判定事由入力","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;破産更生先_発生経緯入力","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;引当金判定画面へ遷移","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;一般債権_概要説明","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;一般債権_画面を下へスクロール","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;一般債権_第１／３四半期フラグ設定","s_27.htm","course"));
var stepFrame28	= new TreeMenu();
var branch28_1 = new TreeMenu();
stepFrame28.addItem(new TreeMenuItem("ブランチ28.1.&nbsp;新規ブランチ","","","","Branch"));
branch28_1.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
branch28_1.addItem(new TreeMenuItem("28.1.1.&nbsp;一般債権_フラグ区分選択①","s_27_0_0.htm","course"));
branch28_1.addItem(new TreeMenuItem("28.1.2.&nbsp;一般債権_フラグ区分選択②","s_27_0_1.htm","course"));
branch28_1.addItem(new TreeMenuItem("28.1.3.&nbsp;一般債権_フラグコメント入力","s_27_0_2.htm","course"));
branch28_1.addItem(new TreeMenuItem("28.1.4.&nbsp;一般債権_第１／３四半期フラグ設定終了","s_27_0_3.htm","course"));
branch28_1.addItem(new TreeMenuItem("28.1.5.&nbsp;終了","s_27_0_4.htm","course"));
stepFrame28.items[0].makeSubmenu(branch28_1);
treeMenu.items[28].makeSubmenu(stepFrame28);
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("29.&nbsp;一般債権_承認担当者選択①","s_28.htm","course"));
treeMenu.addItem(new TreeMenuItem("30.&nbsp;一般債権_承認担当者選択②","s_29.htm","course"));
treeMenu.addItem(new TreeMenuItem("31.&nbsp;一般債権_査定登録","s_30.htm","course"));
treeMenu.addItem(new TreeMenuItem("32.&nbsp;一般債権以外_概要説明","s_31.htm","course"));
treeMenu.addItem(new TreeMenuItem("33.&nbsp;一般債権以外_勘定先CD入力","s_32.htm","course"));
treeMenu.addItem(new TreeMenuItem("34.&nbsp;一般債権以外_取引先名入力","s_33.htm","course"));
treeMenu.addItem(new TreeMenuItem("35.&nbsp;一般債権以外_勘定科目入力","s_34.htm","course"));
treeMenu.addItem(new TreeMenuItem("36.&nbsp;一般債権以外_金額入力","s_35.htm","course"));
treeMenu.addItem(new TreeMenuItem("37.&nbsp;一般債権以外_金額自動反映確認","s_36.htm","course"));
treeMenu.addItem(new TreeMenuItem("38.&nbsp;一般債権以外_不動産担保契約額入力","s_37.htm","course"));
treeMenu.addItem(new TreeMenuItem("39.&nbsp;一般債権以外_不動産担保評価額入力","s_38.htm","course"));
treeMenu.addItem(new TreeMenuItem("40.&nbsp;一般債権以外_動産担保契約額入力","s_39.htm","course"));
treeMenu.addItem(new TreeMenuItem("41.&nbsp;一般債権以外_動産担保評価額入力","s_40.htm","course"));
treeMenu.addItem(new TreeMenuItem("42.&nbsp; 一般債権以外_貿易保険契約額入力","s_41.htm","course"));
treeMenu.addItem(new TreeMenuItem("43.&nbsp;一般債権以外_貿易保険評価額入力","s_42.htm","course"));
treeMenu.addItem(new TreeMenuItem("44.&nbsp;一般債権以外_その他契約額入力","s_43.htm","course"));
treeMenu.addItem(new TreeMenuItem("45.&nbsp;一般債権以外_その他評価額入力","s_44.htm","course"));
treeMenu.addItem(new TreeMenuItem("46.&nbsp;一般債権以外_評価額自動反映確認","s_45.htm","course"));
treeMenu.addItem(new TreeMenuItem("47.&nbsp;一般債権以外_留保債務入力","s_46.htm","course"));
treeMenu.addItem(new TreeMenuItem("48.&nbsp;一般債権以外_第三者留保債務入力","s_47.htm","course"));
treeMenu.addItem(new TreeMenuItem("49.&nbsp;一般債権以外_保全③入力","s_48.htm","course"));
treeMenu.addItem(new TreeMenuItem("50.&nbsp;一般債権以外_その他回収の内容④入力","s_49.htm","course"));
treeMenu.addItem(new TreeMenuItem("51.&nbsp;一般債権以外_履行請求懸念⑤入力","s_50.htm","course"));
treeMenu.addItem(new TreeMenuItem("52.&nbsp;一般債権以外_追加引当金入力","s_51.htm","course"));
treeMenu.addItem(new TreeMenuItem("53.&nbsp;一般債権以外_その他の内容入力","s_52.htm","course"));
treeMenu.addItem(new TreeMenuItem("54.&nbsp;一般債権以外_その他回収の内容入力","s_53.htm","course"));
treeMenu.addItem(new TreeMenuItem("55.&nbsp;一般債権以外_履行請求懸念の内容説明入力","s_54.htm","course"));
treeMenu.addItem(new TreeMenuItem("56.&nbsp;一般債権以外_引当金算定根拠の内容説明入力","s_55.htm","course"));
treeMenu.addItem(new TreeMenuItem("57.&nbsp;一般債権以外_今後の回収見通しなど入力","s_56.htm","course"));
treeMenu.addItem(new TreeMenuItem("58.&nbsp;一般債権以外_第１／３四半期フラグ設定","s_57.htm","course"));
var stepFrame58	= new TreeMenu();
var branch58_1 = new TreeMenu();
stepFrame58.addItem(new TreeMenuItem("ブランチ58.1.&nbsp;新規ブランチ","","","","Branch"));
branch58_1.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
branch58_1.addItem(new TreeMenuItem("58.1.1.&nbsp;一般債権以外_フラグ区分選択①","s_57_0_0.htm","course"));
branch58_1.addItem(new TreeMenuItem("58.1.2.&nbsp;一般債権以外_フラグ区分選択②","s_57_0_1.htm","course"));
branch58_1.addItem(new TreeMenuItem("58.1.3.&nbsp;一般債権以外_フラグコメント入力","s_57_0_2.htm","course"));
branch58_1.addItem(new TreeMenuItem("58.1.4.&nbsp;一般債権以外_第１／３四半期フラグ設定終了","s_57_0_3.htm","course"));
branch58_1.addItem(new TreeMenuItem("58.1.5.&nbsp;終了","s_57_0_4.htm","course"));
stepFrame58.items[0].makeSubmenu(branch58_1);
treeMenu.items[59].makeSubmenu(stepFrame58);
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("59.&nbsp;一般債権以外_承認担当者選択①","s_58.htm","course"));
treeMenu.addItem(new TreeMenuItem("60.&nbsp;一般債権以外_承認担当者選択②","s_59.htm","course"));
treeMenu.addItem(new TreeMenuItem("61.&nbsp;一般債権以外_査定登録","s_60.htm","course"));
treeMenu.addItem(new TreeMenuItem("62.&nbsp;終了","s_61.htm","course"));
