var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（引当金検証登録）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;引当金検証対象の勘定先選択","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;もぎ取り確認","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;取引先区分選択①","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;取引先区分選択②","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;債権区分選択①","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;債権区分選択②","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;引当金算定根拠入力","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;承認担当者選択①","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;承認担当者選択②","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;引当金検証登録","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;終了","s_11.htm","course"));
