var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（査定承認）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;表示件数選択①","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;表示件数選択②","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;承認対象選択","s_3.htm","course"));
var stepFrame4	= new TreeMenu();
var branch4_1 = new TreeMenu();
stepFrame4.addItem(new TreeMenuItem("ブランチ4.1.&nbsp;新規ブランチ","","","","Branch"));
branch4_1.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
branch4_1.addItem(new TreeMenuItem("4.1.1.&nbsp;一括承認実行","s_3_0_0.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.2.&nbsp;個別承認実行","s_3_0_1.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.3.&nbsp;終了","s_3_0_2.htm","course"));
stepFrame4.items[0].makeSubmenu(branch4_1);
treeMenu.items[4].makeSubmenu(stepFrame4);
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;取引先概要タブ選択","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;取引先・差遣区分判定タブ選択","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;引当金判定タブ選択","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;債権明細タブ選択","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;留保債務タブ選択","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;添付参照","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;添付内容照会","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;承認実行","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;終了","s_12.htm","course"));
