var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Select Dept. for transfer(1)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select Dept. for transfer(2)","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Select Person in Charge_input/search","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Select Person in Charge(1)","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Select Person in Charge(2)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Input Transfer Comment","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Ttansfer","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;End","s_7.htm","course"));
