var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（引当金確認）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;勘定先CD選択","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;もぎ取り確認","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;取引先区分選択①","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;取引先区分選択②","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;債権区分選択①","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;債権区分選択②","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;引当金詳細フラグ選択①","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;引当金詳細フラグ選択②","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;区分判定根拠入力","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;承認担当者選択①","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;承認担当者選択②","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;登録実行","s_12.htm","course"));
var stepFrame13	= new TreeMenu();
var branch13_1 = new TreeMenu();
stepFrame13.addItem(new TreeMenuItem("ブランチ13.1.&nbsp;新規ブランチ","","","","Branch"));
branch13_1.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
branch13_1.addItem(new TreeMenuItem("13.1.1.&nbsp;査定結果_フェーズ選択①","s_12_0_0.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.2.&nbsp;査定結果_フェーズ選択②","s_12_0_1.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.3.&nbsp;査定結果_取引先概要タブ選択","s_12_0_2.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.4.&nbsp;査定結果_取引先・債権区分判定タブ選択","s_12_0_3.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.5.&nbsp;査定結果_引当金判定タブ選択","s_12_0_4.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.6.&nbsp;査定結果_債権明細タブ選択","s_12_0_5.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.7.&nbsp;査定結果_留保債務タブ選択","s_12_0_6.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.8.&nbsp;査定結果_添付参照","s_12_0_7.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.9.&nbsp;査定結果_添付照会","s_12_0_8.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.10.&nbsp;査定結果_引当金確認画面へ遷移","s_12_0_9.htm","course"));
branch13_1.addItem(new TreeMenuItem("13.1.11.&nbsp;終了","s_12_0_10.htm","course"));
stepFrame13.items[0].makeSubmenu(branch13_1);
treeMenu.items[13].makeSubmenu(stepFrame13);
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;終了","s_13.htm","course"));
