var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Details of Progress and recovery)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Input Month/Year","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Input a Cust.","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Input a DNUS No.","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Input a Cust.Name","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Select a Country(1)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Select a Country(2)","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Select a Phase(1)","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;Select a Phase(2)","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;Select a Status(1)","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;Select a Status(2)","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;Select a Area(1)","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;Select a Area(2)","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;Select a Co.(1)","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;Select a Co.(2)","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;Select a Cell(1)","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;Select a Cell(2)","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;Input a Related parties","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;Input a date of [from]","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;Input a date of [to]","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;Select a Records(1)","s_20.htm","course"));
treeMenu.addItem(new TreeMenuItem("22.&nbsp;Select a Records(2)","s_21.htm","course"));
treeMenu.addItem(new TreeMenuItem("23.&nbsp;Click a Search button","s_22.htm","course"));
treeMenu.addItem(new TreeMenuItem("24.&nbsp;Move to the screen of details","s_23.htm","course"));
treeMenu.addItem(new TreeMenuItem("25.&nbsp;Screen of details_Judgment on Overdue tub","s_24.htm","course"));
treeMenu.addItem(new TreeMenuItem("26.&nbsp;Screen of details_Assessment tab","s_25.htm","course"));
treeMenu.addItem(new TreeMenuItem("27.&nbsp;Recovery","s_26.htm","course"));
treeMenu.addItem(new TreeMenuItem("28.&nbsp;End","s_27.htm","course"));
