var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;添付ファイル選択①","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;添付ファイル選択②","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;添付ファイル選択③","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;添付ファイル仮登録","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;添付ファイル登録","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;添付選択完了","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;終了","s_6.htm","course"));
