var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Select Assessing period(1)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select Assessing period(2)","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Select Year and Month(1)","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Select Year and Month(2)","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Change Proxy Person Window(1)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Change Proxy Person Window(2)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;End","s_6.htm","course"));
