var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;main menu(Registration of Judgement)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;select Cust.Code for which to input judgement","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;confirm take","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;input details for judgement","s_3.htm","course"));
var stepFrame4	= new TreeMenu();
var branch4_1 = new TreeMenu();
stepFrame4.addItem(new TreeMenuItem("Branch4.1.&nbsp;","","","","Branch"));
branch4_1.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
branch4_1.addItem(new TreeMenuItem("4.1.1.&nbsp;select judgement","s_3_0_0.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.2.&nbsp;move to details screen","s_3_0_1.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.3.&nbsp;input reasons for the Judgement","s_3_0_2.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.4.&nbsp;download_select language","s_3_0_3.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.5.&nbsp;download","s_3_0_4.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.6.&nbsp;download_macro settings","s_3_0_5.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.7.&nbsp;download_editing file (1)","s_3_0_6.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.8.&nbsp;download_select assessment category(1)","s_3_0_7.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.9.&nbsp;download_select assessment category(2)","s_3_0_8.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.10.&nbsp;download_input reasons for Judgement","s_3_0_9.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.11.&nbsp;download_editing file (2)","s_3_0_10.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.12.&nbsp;download_CSV output","s_3_0_11.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.13.&nbsp;download_save in CSV (1)","s_3_0_12.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.14.&nbsp;download_save in CSV (2)","s_3_0_13.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.15.&nbsp;download_close file","s_3_0_14.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.16.&nbsp;download_confirm file save","s_3_0_15.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.17.&nbsp;download_browse file","s_3_0_16.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.18.&nbsp;download_select file(1)","s_3_0_17.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.19.&nbsp;download_select file(2)","s_3_0_18.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.20.&nbsp;download_upload all","s_3_0_19.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.21.&nbsp;end","s_3_0_20.htm","course"));
stepFrame4.items[0].makeSubmenu(branch4_1);
treeMenu.items[4].makeSubmenu(stepFrame4);
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;selection ofJudgement(1)","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;selection ofJudgement(2)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Entry of reason for the Judgement","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Saving details","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;selection of the person in charge of approve(1)","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;selection of the person in charge of approve(2)","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;registration of Judgment","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;end","s_11.htm","course"));
