var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Re-approval of Claim Debt)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select Displaying the number of items(1)","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Select Displaying the number of items(2)","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Select Cust.Code","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Reffer to attachmen","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Inquiry for attachment file","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Approving","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;End","s_7.htm","course"));
