var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu(Approval of Selection)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select the number of indicated item(1)","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Select the number of indicated item(2)","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Select approval target","s_3.htm","course"));
var stepFrame4	= new TreeMenu();
var branch4_1 = new TreeMenu();
stepFrame4.addItem(new TreeMenuItem("Branch4.1.&nbsp;","","","","Branch"));
branch4_1.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
branch4_1.addItem(new TreeMenuItem("4.1.1.&nbsp;Collective Approval","s_3_0_0.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.2.&nbsp;Individual Approval","s_3_0_1.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.3.&nbsp;End","s_3_0_2.htm","course"));
stepFrame4.items[0].makeSubmenu(branch4_1);
treeMenu.items[4].makeSubmenu(stepFrame4);
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Select tab of basic information","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Select the tab of account of credit","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Approval","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;End","s_7.htm","course"));
