var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Main Menu","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Target User_Input input/search","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Target User_Select Person in Charge(1)","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Target User_Select Person in Charge(2)","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Proxy Person_Input input/search ","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Proxy Person_Select Person in Charge(1)","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;Proxy Person_Select Person in Charge(2)","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;Set Up Proxy Person","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;End","s_8.htm","course"));
