var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;滞留判定対象の勘定先選択","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;もぎ取り確認","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;明細の滞留判定設定","s_3.htm","course"));
var stepFrame4	= new TreeMenu();
var branch4_1 = new TreeMenu();
stepFrame4.addItem(new TreeMenuItem("ブランチ4.1.&nbsp;新規ブランチ","","","","Branch"));
branch4_1.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
branch4_1.addItem(new TreeMenuItem("4.1.1.&nbsp;滞留判定選択","s_3_0_0.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.2.&nbsp;詳細画面へ遷移","s_3_0_1.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.3.&nbsp;判定事由入力","s_3_0_2.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.4.&nbsp;ダウンロード_出力言語選択","s_3_0_3.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.5.&nbsp;ダウンロード","s_3_0_4.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.6.&nbsp;ダウンロード_マクロ設定","s_3_0_5.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.7.&nbsp;ダウンロード_ファイル編集①","s_3_0_6.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.8.&nbsp;ダウンロード_判定区分選択①","s_3_0_7.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.9.&nbsp;ダウンロード_判定区分選択②","s_3_0_8.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.10.&nbsp;ダウンロード_判定事由入力","s_3_0_9.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.11.&nbsp;ダウンロード_ファイル編集②","s_3_0_10.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.12.&nbsp;ダウンロード_CSV出力","s_3_0_11.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.13.&nbsp;ダウンロード_CSV保存①","s_3_0_12.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.14.&nbsp;ダウンロード_CSV保存②","s_3_0_13.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.15.&nbsp;ダウンロード_ファイルを閉じる","s_3_0_14.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.16.&nbsp;ダウンロード_ファイル保存確認","s_3_0_15.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.17.&nbsp;ダウンロード_取込ファイル参照","s_3_0_16.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.18.&nbsp;ダウンロード_取込ファイル選択①","s_3_0_17.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.19.&nbsp;ダウンロード_取込ファイル選択②","s_3_0_18.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.20.&nbsp;ダウンロード_一括取込","s_3_0_19.htm","course"));
branch4_1.addItem(new TreeMenuItem("4.1.21.&nbsp;終了","s_3_0_20.htm","course"));
stepFrame4.items[0].makeSubmenu(branch4_1);
treeMenu.items[4].makeSubmenu(stepFrame4);
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;滞留判定選択①","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;滞留判定選択②","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;判定事由入力","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;明細保存","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;承認担当者選択①","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;承認担当者選択②","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;滞留判定登録","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;終了","s_11.htm","course"));
