var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "操作手順";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("債権査定システム","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;メインメニュー（クレーム債権再設定登録）","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;査定期選択①","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;査定期選択②","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;ソート項目選択①","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;ソート項目選択②","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;ソート順選択①","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;ソート順選択②","s_6.htm","course"));
treeMenu.addItem(new TreeMenuItem("8.&nbsp;表示件数選択①","s_7.htm","course"));
treeMenu.addItem(new TreeMenuItem("9.&nbsp;表示件数選択②","s_8.htm","course"));
treeMenu.addItem(new TreeMenuItem("10.&nbsp;勘定先CD選択","s_9.htm","course"));
treeMenu.addItem(new TreeMenuItem("11.&nbsp;もぎ取り確認","s_10.htm","course"));
treeMenu.addItem(new TreeMenuItem("12.&nbsp;コメント表示①","s_11.htm","course"));
treeMenu.addItem(new TreeMenuItem("13.&nbsp;コメント表示②","s_12.htm","course"));
treeMenu.addItem(new TreeMenuItem("14.&nbsp;詳細設定","s_13.htm","course"));
treeMenu.addItem(new TreeMenuItem("15.&nbsp;クレーム債権チェックボックス設定","s_14.htm","course"));
treeMenu.addItem(new TreeMenuItem("16.&nbsp;判定事由入力","s_15.htm","course"));
treeMenu.addItem(new TreeMenuItem("17.&nbsp;明細保存","s_16.htm","course"));
treeMenu.addItem(new TreeMenuItem("18.&nbsp;承認担当者選択①","s_17.htm","course"));
treeMenu.addItem(new TreeMenuItem("19.&nbsp;承認担当者選択②","s_18.htm","course"));
treeMenu.addItem(new TreeMenuItem("20.&nbsp;登録実行","s_19.htm","course"));
treeMenu.addItem(new TreeMenuItem("21.&nbsp;終了","s_20.htm","course"));
