var treeMenu		= new TreeMenu();
var treeMenuName    = "myMenu";
var treeMenuDays    = null;
var treeMenuFrame   = "menuFrame";
var treeMenuImgDir  = "images/";
var treeMenuBgColor = "#FFFFFF";
var treeMenuFgColor = "#000000";
var treeMenuHiBg    = "#99CCFF";
var treeMenuHiFg    = "#FFFFFF";
var treeMenuRoot    = "Operational Procedure";
var treeMenuWidth   = "100%";
var strDoneMsg=' ';
var strCharset='utf-8';
treeMenu.addItem(new TreeMenuItem("Credit Assessment System","","","","WindowCaption"));
treeMenu.addItem(new TreeMenuItem("1.&nbsp;Select attchment file(1)","s_0.htm","course"));
treeMenu.addItem(new TreeMenuItem("2.&nbsp;Select attachment file(2)","s_1.htm","course"));
treeMenu.addItem(new TreeMenuItem("3.&nbsp;Select attachment file(3)","s_2.htm","course"));
treeMenu.addItem(new TreeMenuItem("4.&nbsp;Pre-register attachment file","s_3.htm","course"));
treeMenu.addItem(new TreeMenuItem("5.&nbsp;Register attachment file","s_4.htm","course"));
treeMenu.addItem(new TreeMenuItem("6.&nbsp;Complete selecting attachment file","s_5.htm","course"));
treeMenu.addItem(new TreeMenuItem("7.&nbsp;End","s_6.htm","course"));
